# Generated by Django 3.2.7 on 2023-08-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230805_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='name',
            field=models.CharField(blank=True, max_length=520, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
